export const FETCH_COLLEGE_SUMMARY_REQUEST = "FETCH_COLLEGE_SUMMARY_REQUEST";
export const FETCH_COLLEGE_SUMMARY_SUCCESS = "FETCH_COLLEGE_SUMMARY_SUCCESS";
export const FETCH_COLLEGE_SUMMARY_FAILURE = "FETCH_COLLEGE_SUMMARY_FAILURE";



// Departments API
export const FETCH_DEPARTMENTS_REQUEST = "FETCH_DEPARTMENTS_REQUEST";
export const FETCH_DEPARTMENTS_SUCCESS = "FETCH_DEPARTMENTS_SUCCESS";
export const FETCH_DEPARTMENTS_FAILURE = "FETCH_DEPARTMENTS_FAILURE";


export const SEARCH_DEPARTMENTS_REQUEST = "SEARCH_DEPARTMENTS_REQUEST";
export const SEARCH_DEPARTMENTS_SUCCESS = "SEARCH_DEPARTMENTS_SUCCESS";
export const SEARCH_DEPARTMENTS_FAILURE = "SEARCH_DEPARTMENTS_FAILURE";
