export const FETCH_COLLEGE_SUMMARY_REQUEST = "FETCH_COLLEGE_SUMMARY_REQUEST";
export const FETCH_COLLEGE_SUMMARY_SUCCESS = "FETCH_COLLEGE_SUMMARY_SUCCESS";
export const FETCH_COLLEGE_SUMMARY_FAILURE = "FETCH_COLLEGE_SUMMARY_FAILURE";



// College_Department_Types.js

export const FETCH_COLLEGE_DEPARTMENTS_REQUEST = "FETCH_COLLEGE_DEPARTMENTS_REQUEST";
export const FETCH_COLLEGE_DEPARTMENTS_SUCCESS = "FETCH_COLLEGE_DEPARTMENTS_SUCCESS";
export const FETCH_COLLEGE_DEPARTMENTS_FAILURE = "FETCH_COLLEGE_DEPARTMENTS_FAILURE";



export const SEARCH_DEPARTMENTS_REQUEST = "SEARCH_DEPARTMENTS_REQUEST";
export const SEARCH_DEPARTMENTS_SUCCESS = "SEARCH_DEPARTMENTS_SUCCESS";
export const SEARCH_DEPARTMENTS_FAILURE = "SEARCH_DEPARTMENTS_FAILURE";


export const FETCH_DEPARTMENT_BY_ID_REQUEST = "FETCH_DEPARTMENT_BY_ID_REQUEST";
export const FETCH_DEPARTMENT_BY_ID_SUCCESS = "FETCH_DEPARTMENT_BY_ID_SUCCESS";
export const FETCH_DEPARTMENT_BY_ID_FAILURE = "FETCH_DEPARTMENT_BY_ID_FAILURE";

export const UPDATE_DEPARTMENT_REQUEST = "UPDATE_DEPARTMENT_REQUEST";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_FAILURE = "UPDATE_DEPARTMENT_FAILURE";


export const DELETE_DEPARTMENT_REQUEST = "DELETE_DEPARTMENT_REQUEST";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_FAILURE = "DELETE_DEPARTMENT_FAILURE";
