export const ADD_DEPARTMENT_REQUEST = "ADD_DEPARTMENT_REQUEST";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";


export const FETCH_DEPARTMENTS_REQUEST = "FETCH_DEPARTMENTS_REQUEST";
export const FETCH_DEPARTMENTS_SUCCESS = "FETCH_DEPARTMENTS_SUCCESS";
export const FETCH_DEPARTMENTS_FAILURE = "FETCH_DEPARTMENTS_FAILURE";



export const EDIT_DEPARTMENT_REQUEST = "EDIT_DEPARTMENT_REQUEST";
export const EDIT_DEPARTMENT_SUCCESS = "EDIT_DEPARTMENT_SUCCESS";
export const EDIT_DEPARTMENT_FAILURE = "EDIT_DEPARTMENT_FAILURE";


export const REMOVE_DEPARTMENT_REQUEST = "REMOVE_DEPARTMENT_REQUEST";
export const REMOVE_DEPARTMENT_SUCCESS = "REMOVE_DEPARTMENT_SUCCESS";
export const REMOVE_DEPARTMENT_FAILURE = "REMOVE_DEPARTMENT_FAILURE";

export const SEARCH_DEPARTMENT_REQUEST = "SEARCH_DEPARTMENT_REQUEST";
export const SEARCH_DEPARTMENT_SUCCESS = "SEARCH_DEPARTMENT_SUCCESS";
export const SEARCH_DEPARTMENT_FAILURE = "SEARCH_DEPARTMENT_FAILURE";
