export const FETCH_DEPT_COUNT_REQUEST = "FETCH_DEPT_COUNT_REQUEST";
export const FETCH_DEPT_COUNT_SUCCESS = "FETCH_DEPT_COUNT_SUCCESS";
export const FETCH_DEPT_COUNT_FAILURE = "FETCH_DEPT_COUNT_FAILURE";


export const FETCH_DEPT_TABLE_REQUEST = "FETCH_DEPT_TABLE_REQUEST";
export const FETCH_DEPT_TABLE_SUCCESS = "FETCH_DEPT_TABLE_SUCCESS";
export const FETCH_DEPT_TABLE_FAILURE = "FETCH_DEPT_TABLE_FAILURE";

// Filter


export const FETCH_DEPT_FILTER_REQUEST = "FETCH_DEPT_FILTER_REQUEST";
export const FETCH_DEPT_FILTER_SUCCESS = "FETCH_DEPT_FILTER_SUCCESS";
export const FETCH_DEPT_FILTER_FAILURE = "FETCH_DEPT_FILTER_FAILURE";
