export const GET_MENTOR_REQUEST = "GET_MENTOR_REQUEST";
export const GET_MENTOR_SUCCESS = "GET_MENTOR_SUCCESS";
export const GET_MENTOR_FAILURE = "GET_MENTOR_FAILURE";

export const STUDENTS_WITHOUT_MENTOR_REQUEST = "STUDENTS_WITHOUT_MENTOR_REQUEST";
export const STUDENTS_WITHOUT_MENTOR_SUCCESS = "STUDENTS_WITHOUT_MENTOR_SUCCESS";
export const STUDENTS_WITHOUT_MENTOR_FAILURE = "STUDENTS_WITHOUT_MENTOR_FAILURE";