export const GET_MENTOR_REQUEST = "GET_MENTOR_REQUEST";
export const GET_MENTOR_SUCCESS = "GET_MENTOR_SUCCESS";
export const GET_MENTOR_FAILURE = "GET_MENTOR_FAILURE";

export const STUDENTS_WITHOUT_MENTOR_REQUEST = "STUDENTS_WITHOUT_MENTOR_REQUEST";
export const STUDENTS_WITHOUT_MENTOR_SUCCESS = "STUDENTS_WITHOUT_MENTOR_SUCCESS";
export const STUDENTS_WITHOUT_MENTOR_FAILURE = "STUDENTS_WITHOUT_MENTOR_FAILURE";

export const AVERAGE_STUDENTS_REQUEST = "AVERAGE_STUDENTS_REQUEST";
export const AVERAGE_STUDENTS_SUCCESS = "AVERAGE_STUDENTS_SUCCESS";
export const AVERAGE_STUDENTS_FAILURE = "AVERAGE_STUDENTS_FAILURE";

export const TOP_PERFORMING_REQUEST = "TOP_PERFORMING_REQUEST";
export const TOP_PERFORMING_SUCCESS = "TOP_PERFORMING_SUCCESS";
export const TOP_PERFORMING_FAILURE = "TOP_PERFORMING_FAILURE";

export const DEPARTMENT_INFORMATION_REQUEST = "DEPARTMENT_INFORMATION_REQUEST";
export const DEPARTMENT_INFORMATION_SUCCESS = "DEPARTMENT_INFORMATION_SUCCESS";
export const DEPARTMENT_INFORMATION_FAILURE = "DEPARTMENT_INFORMATION_FAILURE";

export const SEARCH_MENTOR_REQUEST = "SEARCH_MENTOR_REQUEST";
export const SEARCH_MENTOR_SUCCESS = "SEARCH_MENTOR_SUCCESS";
export const SEARCH_MENTOR_FAILURE = "SEARCH_MENTOR_FAILURE";