export const FETCH_SUPERADMIN_SUMMARY_REQUEST = "FETCH_SUPERADMIN_SUMMARY_REQUEST";
export const FETCH_SUPERADMIN_SUMMARY_SUCCESS = "FETCH_SUPERADMIN_SUMMARY_SUCCESS";
export const FETCH_SUPERADMIN_SUMMARY_FAILURE = "FETCH_SUPERADMIN_SUMMARY_FAILURE";

export const FETCH_COLLEGES_REQUEST = "FETCH_COLLEGES_REQUEST";
export const FETCH_COLLEGES_SUCCESS = "FETCH_COLLEGES_SUCCESS";
export const FETCH_COLLEGES_FAILURE = "FETCH_COLLEGES_FAILURE";

export const UPDATE_COLLEGE_STATUS_REQUEST = "UPDATE_COLLEGE_STATUS_REQUEST";
export const UPDATE_COLLEGE_STATUS_SUCCESS = "UPDATE_COLLEGE_STATUS_SUCCESS";
export const UPDATE_COLLEGE_STATUS_FAILURE = "UPDATE_COLLEGE_STATUS_FAILURE";

